# Generated by Django 2.1.5 on 2019-02-03 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 20, 29, 41, 715209, tzinfo=utc)),
        ),
    ]
